server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://10.66.203.28:3306/bank_suite_seylan_real_new_qa?allowPublicKeyRetrieval=true&useSSL=false
    password: Seylan@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
